export const itemData = [
  {
    id: 1,
    image: "/assets/images/image1.png",
    heading: "Easy Integrations",
    desc: "Sometrlkn dfnsdfsdfcjl",
    title: "",
  },
  {
    id: 2,
    image: "/assets/images/image1.png",
    heading: "Easy Integrations",
    desc: "Sometrlkn dfnsdfsdfcjl",
    title: "Build for someone",
  },
  {
    id: 3,
    image: "/assets/images/image1.png",
    heading: "Easy Integrations",
    desc: "Sometrlkn dfnsdfsdfcjl",
    title: "",
  },
  {
    id: 4,
    image: "/assets/images/image1.png",
    heading: "Easy Integrations",
    desc: "Sometrlkn dfnsdfsdfcjl",
    title: "",
  },
  {
    id: 5,
    image: "/assets/images/image1.png",
    heading: "Easy Integrations",
    desc: "Sometrlkn dfnsdfsdfcjl",
    title: "Build for someone",
  },
  {
    id: 6,
    image: "/assets/images/image1.png",
    heading: "Easy Integrations",
    desc: "Sometrlkn dfnsdfsdfcjl",
    title: "",
  },
  {
    id: 7,
    image: "/assets/images/image1.png",
    heading: "Easy Integrations",
    desc: "Sometrlkn dfnsdfsdfcjl",
    title: "",
  },
  {
    id: 8,
    image: "/assets/images/image1.png",
    heading: "Easy Integrations",
    desc: "Sometrlkn dfnsdfsdfcjl",
    title: "Build for someone",
  },
  {
    id: 6,
    image: "/assets/images/image1.png",
    heading: "Easy Integrations",
    desc: "Sometrlkn dfnsdfsdfcjl",
    title: "",
  },
];
